'use strict';
export default [
    // PC
    "shopex.html",
    "iptv.html",
    "zlc.html",
    "cfy.html",
    "cflc.html",
    "ydgwc.html",
    "xhh.html",
    "wzjg.html",
    "wsy.html",
    "wbccht.html",
    "trj.html",
    "tbj.html",
    "tbs.html",
    "spzl.html",
    "rzy.html",
    "pjj.html",
    "lmcc.html",
    "lcc.html",
    "jy.html",
    "dz.html",
    "blgds.html",
    "bknc.html",
    // APP
    "appCflc.html",    
    "appCfy.html",    
    "appPjj.html",    
    "appRzy.html",    
    "appSphd.html",    
    "appTbj.html",    
    "appThg.html",    
    "appTrj.html",    
    "appTxs.html",    
    "appXhh.html",    
    "appZlc.html",    
    "ubl.html",    
    "ubsp.html",   
    // XX
    "xxAhz.html", 
    "xxGjsd.html", 
    "xxMbkp.html", 
    "xxQgmp.html", 
    "xxShanti.html", 
    "xxShantiZn.html", 
    "xxShsq.html", 
    "xxSqbw.html", 
    "xxSzhq.html", 
    "xxXhh.html", 
    "xxZjsh.html", 
    "xxZjyg.html", 
    // ZT
    "ztLqkj.html", 
    "ztPjj.html", 
    "ztTbsj.html", 
    "ztTxs.html", 
    "ztXhh.html", 
    "ztXhhfl.html", 
    "ztZlc.html"
];